# Generated by Django 5.2.8 on 2025-11-26 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productotalla',
            options={'verbose_name': 'Stock por Talla', 'verbose_name_plural': 'Stock por Tallas'},
        ),
        migrations.AlterModelOptions(
            name='talla',
            options={'verbose_name': 'Talla', 'verbose_name_plural': 'Tallas'},
        ),
    ]
