# Generated by Django 5.2.8 on 2025-11-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='A Medias Tintas', max_length=100)),
                ('email_contacto', models.EmailField(default='contacto@amediastintas.cl', max_length=254)),
                ('telefono', models.CharField(default='+56912345678', max_length=15)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('envio_gratis_desde', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
